### ISSUE TITLE
Please bump version after release.

### ISSUE THREAD

**Issue by cheako** [ash-rs/ash#224]
Use case:
[patch.crates-io]
ash = { git = 'https://github.com/MaikKlein/ash.git' }

If the version in git is not ahead of creats-io then things get confusing.  If you NEED to increment the version as part of a release, then consider using an patch is even=release/odd=dev nomenclature.

Thanks.

**Comment by MaikKlein** [comment]
Can you describe the problem a bit more? What is confusing? What is the problem with `[patch.crates-io]`? Right now the version of crates.io and master are always the same.

**Comment by cheako** [comment]
Yes, the problem is that the version numbers are the same even though the features are different.

The issue is when other crates depend on a git revision, tag, or branch.  The version matches with crates.io, but the version being depended on is different.  The contents in git should reflect that.

BTW I've published a crate that incorporates ash from master and am using it in my other crates.  https://gitlab.com/cheako/ash-tray-rs/blob/master/rebase-ash.sh this script fixes some lint issues within ash AND OTHER THINGS.

Here's an example of what I'm talking about, I've published 0.1.0 and the bumped the version in git.
https://gitlab.com/cheako/ash-tray-rs/commits/master

**Comment by cheako** [comment]
On my laptop now instead of my phone.  For the OP I didn't include a ```version = "XXX",``` because the version in git is /wrong/ and it would look funny to depend on the same version that could be obtained without using a ```[patch]```.

There is one more consideration,beyond bumping the version after a release.  That is to remember to appropriately update the version while(in the same commit) introducing breaking changes, at least for the FIRST breaking change.  This will help also.

**Comment by aloucks** [comment]
What you're describing sounds similar to the Java ecosystem where the version number is often bumped on master with a `-SNAPSHOT` suffix.

From what I've seen, the rust ecosystem does not follow that convention and generally leaves master with the version number last pushed to crates.io. I believe the `[patch]` section of `Cargo.toml` somewhat expects that too when applying to transitive dependencies. 

I believe ash is following the precedent set by the rest of the ecosystem in terms of versioning and what's on master, although it's possible that I'm misunderstanding. Do you examples of the contrary?

**Comment by cheako** [comment]
No, but if everyone else jumps off a bridge do you follow?

I only report the problem where I've personally experienced an issue.  If rust should adopt something like what Java does, I wouldn't know where to discuss it.   I've seen '-'s in rust crate versions on crates.io, so I don't think anything is stopping adopting this right now...  Especially since this change mainly effect git checkouts.

**Comment by MaikKlein** [comment]
To be honest I'd rather update breaking changes right before I publish them. But what I wanted to do for a long time now is to maintain git tags for published versions. I assume that would fix your issue? So instead of rebasing of master, you could rebase of a specific commit (the same commit as on crates.io). I probably should also create a new github release.

Also is there any reason for not creating a PR?

**Comment by cheako** [comment]
I think a PR is an overwhelming complex way to change a few bytes.  The bigger issue is awareness.

I don't think tags would help at all, every commit is already tagged with a revision id.  The issue is that we can already rebase(both in git and with the patch feature of cargo) off any revisions, but there is no revision that contains the correct information.  We need the version indicated in Cargo.toml to reflect the code that exists in the *.rs files and previously master had the previous version id.

**Comment by MarijnS95** [comment]
It doesn't seem like anyone really understands what you're requesting. As already said by @aloucks, the version in a repository _has to match the version published on crates.io for `[patch.crates-io]` to be allowed_. That is, if we were to eagerly bump the version in this repository ahead of publishing, you won't be able to patch to a newer version anymore.

Then it is up to you to select a patch with a `rev =` that is compatible with your codebase, or fix compatibility issues if it doesn't. This is generally only done if you want to prepare for an upcoming breaking Ash release, or need a breaking bugfix that isn't available on the backport branch/releases. That backport branch should never contain breaking changes as it will be used to publish patch releases from.

---

The only "advantage" in eagerly/early bumping `version` on `master` is when multiple crates in your dependency graph use `ash`. Those are not affected by the patch if they're (for example) on `ash = "0.37"`, but you set the dependency in your own crate to `ash = "0.38"` (works even if unreleased) together with `[patch.crates-io] ash = { git = "..", rev = "something with version 0.38" }`. But then it is impossible to interface with those dependencies as their types from 0.37 and 0.38 will be incompatible.

The same can be achieved anyway without `[patch.crates-io]` by setting `[dependencies] ash = ...` to a `git` reference directly (that won't affect other crates in a dependency graph) so it's a non-argument/non-advantage in the end.
