### ISSUE TITLE
SubmitInfoBuilder: have two slices, but only one count.

### ISSUE THREAD

**Issue by cheako** [ash-rs/ash#239]
wait_semaphore_count is shared by p_wait_semaphores and p_wait_dst_stage_mask, but there are two functions used to set these and they can be passed different counts.  This silently leads to crashes that validation layers don't catch.

**Comment by aloucks** [comment]
I believe the documentation is stating that it's your responsibility to assert those arrays are of the same length. 

https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkSubmitInfo.html

> ## Valid Usage (Implicit)
> If `waitSemaphoreCount` is not `0`, `pWaitSemaphores` must be a valid pointer to an array of `waitSemaphoreCount` valid `VkSemaphore` handles
>
> If `waitSemaphoreCount` is not `0`, `pWaitDstStageMask` must be a valid pointer to an array of `waitSemaphoreCount` valid combinations of `VkPipelineStageFlagBits` values

**Comment by MarijnS95** [comment]
We had a newer report about this in #445, with some more context, so I'll close this as duplicate.  It's still something I'd like to clean up in the next breaking release though.
