### ISSUE TITLE
pipeline_cache in create_graphics_pipelines should be an Option

### ISSUE THREAD

**Issue by malte-v** [ash-rs/ash#261]
In the specification, the parameter `pipelineCache` of `vkCreateGraphicsPipelines` is defined as optional:

> pipelineCache is either VK_NULL_HANDLE, indicating that pipeline caching is disabled; or the handle of a valid pipeline cache object, in which case use of that cache is enabled for the duration of the command.

>         <command successcodes="VK_SUCCESS" errorcodes="VK_ERROR_OUT_OF_HOST_MEMORY,VK_ERROR_OUT_OF_DEVICE_MEMORY,VK_ERROR_INVALID_SHADER_NV">
>             <proto><type>VkResult</type> <name>vkCreateGraphicsPipelines</name></proto>
>             <param><type>VkDevice</type> <name>device</name></param>
>
>             <param optional="true"><type>VkPipelineCache</type> <name>pipelineCache</name></param>
>
>             <param><type>uint32_t</type> <name>createInfoCount</name></param>
>             <param len="createInfoCount">const <type>VkGraphicsPipelineCreateInfo</type>* <name>pCreateInfos</name></param>
>             <param optional="true">const <type>VkAllocationCallbacks</type>* <name>pAllocator</name></param>
>             <param len="createInfoCount"><type>VkPipeline</type>* <name>pPipelines</name></param>
>         </command>

Therefore `pipeline_cache` in `create_graphics_pipelines` should also be an `Option`.

**Comment by MaikKlein** [comment]
We have a PR that make some handles optional https://github.com/MaikKlein/ash/pull/96 but it is blocked on https://github.com/KhronosGroup/Vulkan-Docs/pull/759

Meanwhile you can also just pass `vk::PipelineCache::null()`.
