### ISSUE TITLE
Writing ICD(s) in Rust

### ISSUE THREAD

**Issue by cheako** [ash-rs/ash#575]
Along with #573 some patterns, useful for Layers, are applicable to device drivers.

* An Iterator over vk::BaseInStructure
* Picking members out of such an iterator.

https://gitlab.com/cheako/vk-layer-cache/-/blob/ff04a089e3335ef1823ec5280781b9be14fcc0f3/src/handlers/types.rs

**Comment by MarijnS95** [comment]
Assuming with "iterator over `vk::BaseInStructure` members" you are referring to iterating over `pNext` chains and casting to the corresponding type based on `sType` tag, this was implemented in https://github.com/ash-rs/ash/pull/614.

Other than that Mesa developers are already experimenting with Rust-written Vulkan drivers (https://www.collabora.com/news-and-blog/blog/2023/02/02/exploring-rust-for-vulkan-drivers-part-1/) and I've already given them my full support to cater Ash to that use-case _if they wish to use it_. Until that happens, which appears to be the most concrete endeavour for Rust-written ICDs, there's nothing actionable here (beyond the `Base*Structure` matching that was already implemented) and I'll close this issue.
