### ISSUE TITLE
Add documentation for features.

### ISSUE THREAD

**Issue by nikitablack** [ash-rs/ash#583]
In the documentation, I can see 5 features:

1. default
2. loaded
3. debug
4. libloading
5. linked

Features 1, 2, 3, 4 are enabled by default.

Could you please describe what all these features do?

**Comment by MarijnS95** [comment]
https://github.com/MaikKlein/ash#optional-linking

`libloading` is not a feature but an `optional=true` crate (meta-feature if you wish).

**Comment by nikitablack** [comment]
Thank you.

I personally first searched in docs, then in the readme. Obviously, I couldn't find anything. I didn't look into the sources. If it is not a big effort, it would be good to have it documented in library docs.
