### ISSUE TITLE
ash::Instance::create_device needs clarification on dropping

### ISSUE THREAD

**Issue by ishitatsuyuki** [ash-rs/ash#624]
The create_device docs says:
```
    /// # Safety
    /// In order for the created [`Device`] to be valid for the duration of its
    /// usage, the [`Instance`] this was called on must be dropped later than the
    /// resulting [`Device`].
```

However, AFAIK `Instance` doesn't implement `Drop` and what this means is probably `destroy_instance` must be called after `Device::destroy_device` is called.

Is this correct? If so, the doc comment should be reworded to not use the Rust keyword "drop".

**Comment by MarijnS95** [comment]
Thanks for reporting this! Looks like a bad copy-paste from the `Entry` docs where this is true; I've opened #625 to rectify it.
