### ISSUE TITLE
Make the Handle trait public

### ISSUE THREAD

**Issue by Makogan** [ash-rs/ash#647]
I am dealing with the following issue.

I am using the GLFW crate ion addition with ash. I want to give glfw the handle to a surface object and to the isntance to make a surface for my program.

In the source code I see:

```rust
 impl Handle for $name {
            const TYPE: ObjectType = ObjectType::$ty;
            fn as_raw(self) -> u64 {
                self.0 as u64
            }
            fn from_raw(x: u64) -> Self {
                Self(x as _)
            }
        }
 ```
 
 It would be very useful if the 2 functions in that trait were made public, as it would allow users to interface with any other crate that also tries to interact with vulkan and the windowing system.

**Comment by Ralith** [comment]
[It is public.](https://docs.rs/ash/0.37.0+1.3.209/ash/vk/trait.Handle.html)
