### ISSUE TITLE
generator doesn't run `rustfmt`

### ISSUE THREAD

**Issue by BeastLe9enD** [ash-rs/ash#653]
Hey, I want to add support for `VK_EXT_mesh_shader` to ash. Unfortunately I have a problem running the generator. There are extra spaces between the code.
```Rust
use std :: fmt ; use crate :: vk :: bitflags :: * ; use crate :: vk :: definitions :: * ; use crate :: vk :: enums :: * ;
```
I did the following to get the ash generator running:
* I downloaded `LLVM` for `bindgen` and set `LIBCLANG_PATH` to `C:\Program Files\LLVM\bin`.
* I cloned the newest version of ash
* I ran `cargo run --release --bin generator` from the root directory.

The generator runs without issues, but the code looks weird. Running `cargo fmt` works, I just was curious if its a bug or just intended behaviour.

**Comment by filnet** [comment]
I ran into the same issue a while back.  See https://github.com/ash-rs/ash/pull/305.
Try to update your crates.
