### ISSUE TITLE
`VK_EXT_debug_utils` function inconsistency

### ISSUE THREAD

**Issue by BeastLe9enD** [ash-rs/ash#660]
Inside the Debug Utils loader, the function is called `debug_utils_set_object_name`, but should be called `set_debug_utils_object_name` in my opinion. Is there a good reason for that?
The same is with `debug_utils_set_object_tag`.

Just wanted to point that out in case it was accidental.

https://github.com/ash-rs/ash/blob/b4fc3340836c9b304c2018324e4f9175052f606a/ash/src/extensions/ext/debug_utils.rs#L24

**Comment by Ralith** [comment]
Looks like a mistake to me, good catch! We should add the proper names and deprecate the existing ones.
