### ISSUE TITLE
Missing dynamic state enum variants

### ISSUE THREAD

**Issue by coffeenotfound** [ash-rs/ash#680]
Right now `ash::vk::DynamicState` is missing all variants added by extensions, e.g. `VK_DYNAMIC_STATE_RASTERIZATION_SAMPLES_EXT`

**Comment by MarijnS95** [comment]
Since you commented on #671, note that this is part of Vulkan `1.3.230` which has yet to be merged in #667?

https://github.com/ash-rs/ash/blob/2e5a07b4040c555e7171649a962b610dfd4033f6/ash/src/vk/extensions.rs#L23848

**Comment by coffeenotfound** [comment]
Ah makes sense. Also I'm kind of amazed by the absolute speed you comment on issues
