### ISSUE TITLE
Wayland get_physical_surface_capabilities() returns wrong current_extent

### ISSUE THREAD

**Issue by sudokit** [ash-rs/ash#690]
Im trying to write a simple vulkan initialization program with ash. I need to get the surface extent for the swapchain image_extent. Im trying to get it via get_physical_device_capabilities and from that the current_extent. Im getting the u32::MAX value. I can't confirm if its a wayland thing or specific to my code thing. 

```rust
let capabilities: vk::SurfaceCapabilitiesKHR =
            window.capabilities(device.physical_device)?;
```
```rust
.image_extent(capabilities.current_extent)
```
```rust
pub fn capabilities(
        &self,
        physical_device: vk::PhysicalDevice,
    ) -> Result<vk::SurfaceCapabilitiesKHR, vk::Result> {
        unsafe {
            self.surface_loader
                .get_physical_device_surface_capabilities(physical_device, self.surface)
        }
    }
```

**Comment by MarijnS95** [comment]
This isn't an `ash` issue, and the behaviour is very well documented:

https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSurfaceCapabilitiesKHR.html

> currentExtent is the current width and height of the surface, or the special value (0xFFFFFFFF, 0xFFFFFFFF) indicating that the surface size will be determined by the extent of a swapchain targeting the surface.
