### ISSUE TITLE
Compiler optimizations lead to broken code.

### ISSUE THREAD

**Issue by skibon02** [ash-rs/ash#699]
I am learning Rust, as well as crates ash and glfw. When i was working on Hello Triangle application, i have found really strangle behavior of rust optimization.

Firstly, I have a code with all stuff related to vulkan moved to a separate module. There is a structure `VulkanApp` with all ash and vulkan objects. Also, there is an associated function new, which is creating instance, devices, swapchain, pipeline etc. 
[Initial example](https://github.com/skibon02/rust-vulkan)
Another repository is boiled down version with exactly the same error in the same place:
[Simplified version](https://github.com/skibon02/rust-vulkan-mre)

rust-vulkan-mre have `opt-level = 1` in toml file and with this option it gives me a validation error:
<details>
<summary>Validation error</summary>

```
ERROR VALIDATION: Validation Error: [ VUID-VkDeviceQueueCreateInfo-sType-sType ] 
Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_DEVICE;
 | MessageID = 0x2652a8ef | vkCreateDevice: parameter pCreateInfo->pQueueCreateInfos[0]. sType must be
 VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO The Vulkan spec states: 
sType must be VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO 
(https://vulkan.lunarg.com/doc/view/1.3.236.0/linux/1.3-extensions/vkspec.html#VUID-VkDeviceQueueCreateInfo-sType-sType)
```
</details>

```rust
let queue_create_info = vk::DeviceQueueCreateInfo::builder()
    .queue_family_index(queue_family_index)
    .queue_priorities(&[1.0])
    .build();
let device_create_info = vk::DeviceCreateInfo::builder()
    .queue_create_infos(&[queue_create_info])
    .enabled_extension_names(&device_extensions)
    .enabled_layer_names(&validation_layers).build();

// Error here when opt-level > 0:
let device = unsafe { 
    instance.create_device(physical_device, &device_create_info, None).unwrap()
};
```

When I use default value for debug profile: `opt-level=0`, code runs without errors.

What is the reason for such behavior? Code from ash library? Aggressive rust optimizations? Or maybe both of them.
I saw an [issue](https://github.com/ash-rs/ash/issues/225) with similar symptoms but i don't know how to track when Drop for entry is called. But in initial example i keep entry in the struct as well. Or returning ash::entry::Entry from function is equivalent to Drop here?  
Another observations:
When i move everything to the same module, it works without validation errors. The same is true for `codegen-units=1` option. 
Also it works when i don't return device from function  which is strange.

And one more thing that makes everything even more weird:
When i followed message in validation error, i decided to check value `device_create_info.p_queue_create_infos.s_type.__0`. 
Before creating device it is equal to 2, that is the right value, corresponding to VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO. But after calling `create_device`, it is modified to strange arbitrary number (for example, `1441180368`). Why does call to a function modifies it's arguments?

Before call:
![image](https://user-images.githubusercontent.com/25740003/213922599-301a45a5-8332-4776-9143-ec2224815d0f.png)
After call:
![image](https://user-images.githubusercontent.com/25740003/213922634-e3711663-dfa3-42b9-9553-92d5837b0a89.png)

**Comment by MarijnS95** [comment]
Have you read the section of _not calling `.build()`_ in the readme? That makes the builder lose all lifetime info, which would have otherwise pointed out that you have quite a few temporary arrays that disappear after a statement.

Fortunately we have a breaking change on `master` that alleviates this by storing the lifetime directly on the structs and getting rid of the builders entirely, but this has not yet made it into a _breaking_ release.

**Comment by skibon02** [comment]
Alright, i understand it now. Thanks a lot for the explanation!
