### ISSUE TITLE
Fix or opt out of `clippy::uninlined_format_args`?

### ISSUE THREAD

**Issue by MarijnS95** [ash-rs/ash#704]
https://rust-lang.github.io/rust-clippy/master/#uninlined_format_args

Clippy now warns on this by default in Rust 1.66, while it was only added in [Rust 1.58](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html) 48 weeks prior. I've been keeping it out of my own projects to not bump MSRV unnecessarily and to keep peers happy.

We'd be fine doing this though (in `ash/build.rs`!, the generator and examples) as our MSRV is already 1.59, but the question is whether we should. @Ralith how do you feel about the new format?

**Comment by Ralith** [comment]
I also don't really appreciate clippy forcing such abrupt stylistic churn, but (unlike some other recent lints) I ultimately agree that the recommended change improves readability. I don't think we need to be in any particular hurry, though.

**Comment by filnet** [comment]
I'll take a look at fixing the new warnings.

**Comment by MarijnS95** [comment]
@filnet please don't rush PRs like this; I opened this issue specifically to discuss a direction _prior to_ whipping up PRs guns-blazing.

I'm inclined to skip it for now since this "abrupt forcing of stylistic churn" has been toned back down to `pedantic` in the [already-published Rust 1.67.1 release](https://blog.rust-lang.org/2023/02/09/Rust-1.67.1.html).

**Comment by filnet** [comment]
@MarijnS95 I'll try to curb my enthusiasm.

Note that the lint is "temporarily downgraded to pedantic". Might come back.

**Comment by MarijnS95** [comment]
@filnet thanks.

It'll surely come back, hopefully in a less pronounced manner. At this point I may just be judging the lint based on the way it is being forced into the ecosystem rather than objectively appreciating the readability improvements (though folks close to me disagree... :upside_down_face:). Let's get it over with.

**Comment by MarijnS95** [comment]
Same for regular member access, `write!(..., "{self.foo:?}")` won't work either :(
