### ISSUE TITLE
[Bug] Unable to find symbols for `ApplicationInfo` and `InstanceCreateInfo` in 0.37.0

### ISSUE THREAD

**Issue by LouChiSoft** [ash-rs/ash#711]
Hi, not entirely sure why. But if I use any version of ash in 0.37.0 then you are unable to find symbols for `ApplicationInfo` and `InstanceCreateInfo`. There may be more but this is as far as I got without auto-complete before trying to figure out why. The code still builds just fine, you just don't get any auto-complete for functions or traits, etc.

**Comment by Ralith** [comment]
If the code compiles, then this is an issue with whatever tool you're using that is malfunctioning, not with ash.

**Comment by LouChiSoft** [comment]
I thought that might be the case, but it finds it just fine in other versions and I don't know why it wouldn't for the latest. I am just using the Rust extension for CLion (which IIRC uses my rust toolchains rust-analyzer)

**Comment by Ralith** [comment]
You should report a bug with the author of the malfunctioning tool.

**Comment by MarijnS95** [comment]
Retitled, this can't possibly be an ash bug when it builds successfully (if anything caused by the sheer size of the bindings, it's an inconvenience).

For reference I'm pretty sure rust-analyzer is just fine on the latest ash bindings within vscode, I'm using it right about every day.
