### ISSUE TITLE
get_physical_device_surface_capabilities2 should take a mutable reference to vk::SurfaceCapabilities2KHR

### ISSUE THREAD

**Issue by JoshuaMasci** [ash-rs/ash#740]
The function `vkGetPhysicalDeviceSurfaceCapabilities2KHR` can be extended by use of `VkSurfaceCapabilitiesKHR.pNext`, however the current wrapper `get_physical_device_surface_capabilities2` doesn't allow this since it creates and returns the struct  `vk::SurfaceCapabilities2KHR`. 

To allow the use of the `pNext` pointer,  the function `get_physical_device_surface_capabilities2` should be changed from this:
```rust
  pub unsafe fn get_physical_device_surface_capabilities2(
      &self,
      physical_device: vk::PhysicalDevice,
      surface_info: &vk::PhysicalDeviceSurfaceInfo2KHR,
  ) -> VkResult<vk::SurfaceCapabilities2KHR>
```
To something like this:
```rust
  pub unsafe fn get_physical_device_surface_capabilities2(
      &self,
      physical_device: vk::PhysicalDevice,
      surface_info: &vk::PhysicalDeviceSurfaceInfo2KHR,
      surface_capabilities: &mut vk::SurfaceCapabilities2KHR,
  ) -> VkResult<()>
```

**Comment by MarijnS95** [comment]
We've had discussions about how to best pass these types in the past and fixed most functions to allow this (e.g. #588), but it seems like it was forgotten about when this extension was originally wrapped in https://github.com/ash-rs/ash/pull/530. Especially considering that `VkSurfaceCapabilities2KHR` exists solely to represent `VkSurfaceCapabilitiesKHR` but with `sType` and `pNext` fields 😅.

It looks like at least [`VkSurfacePresentModeEXT`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSurfacePresentModeEXT.html) is relying on this behaviour currently.
