### ISSUE TITLE
`ash::vk::Display` is defined as `*const c_void` while it should just be `c_void`

### ISSUE THREAD

**Issue by naegi** [ash-rs/ash#749]
This is not a big issue but it makes it's usage confusing in
- `XlibSurface::get_physical_device_xlib_presentation_support`  (takes a `&mut Display`)
-  `vk::XlibSurfaceCreateInfoKHR` (takes a `*mut Display`)

**Comment by MarijnS95** [comment]
You're right that `Xlib.h` does _not_ define `Display` as a pointer, but as a typedef to a forward-declared struct:

```c
typedef struct _XDisplay Display;
```

And everything in C uses it as `Display *`. We have double pointers in our implementation that effectively confuse how `Display` is supposed to be used.

What I'll do is change `get_physical_device_xlib_presentation_support()` to take a `*mut Display` instead, and change the type alias to `c_void`.
