### ISSUE TITLE
`string_vkresult`

### ISSUE THREAD

**Issue by freddycansic** [ash-rs/ash#750]
Is there any way to access this function using ash? Thanks

**Comment by MarijnS95** [comment]
This function is not exposed in Vulkan and seems to come from the validation layers:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/314e5389abcc8493067951a6af73b352cd19000e/layers/generated/vk_enum_string_helper.h#L35-L138

We however implement the same functionality ourselves behind the `Debug` trait for `vk::Result`:

https://github.com/ash-rs/ash/blob/1374996499904eb10a665c4df2dae4db70659052/ash/src/vk/enums.rs#L2885-L2965

Unfortunately this requires a `Formatter`; if inconvenient we could always move this to a separate `pub fn to_str(self) -> Option<&'static str>` function that is used by the `Debug` formatter.

---

Note also that we print the friendly comment (from `vk.xml`) in the `Display` implementation:

https://github.com/ash-rs/ash/blob/1374996499904eb10a665c4df2dae4db70659052/ash/src/vk/enums.rs#L991-L1000

**Comment by freddycansic** [comment]
Thanks a lot
