### ISSUE TITLE
Enabled `lto` breaks Vulkan. 

### ISSUE THREAD

**Issue by Jerrody** [ash-rs/ash#764]
### Error

```rs
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ERROR_LAYER_NOT_PRESENT', src\no_engine.rs:129:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\release\vulkan_learn.exe` (exit code: 101)
```

### Code

```toml
ash = { git = "https://github.com/ash-rs/ash" }

[profile.release]
lto = true
```

```rs
unsafe { entry.create_instance(&instance_info, None).unwrap() }
```

**Comment by Jerrody** [comment]
Okay, that's really wierd. It seems that problem is in codegen, somehow, compiler optimizes it that as final modified version is changed and at the result, occurs an error:
```rs
    pub const VALIDATION_LAYER_NAME: &'static str = "VK_LAYER_KHRONOS_validation";
```

If use `println!` it interrupts some (unknown) optimizations.

**Comment by MarijnS95** [comment]
@Jerrody how are you passing this string to Vulkan? Rust str's don't have a trailing null character, you need to pass a `CStr`.

**Comment by Jerrody** [comment]
> @Jerrody how are you passing this string to Vulkan? Rust `str`s don't have a trailing null character, you need to pass a `CStr`.

```rs
        let required_validation_layers = [Self::VALIDATION_LAYER_NAME.as_ptr() as _];
```

**Comment by Jerrody** [comment]
I think this is compiler issue. Without `lto` it works great.

**Comment by MarijnS95** [comment]
@Jerrody as said don't do that, use `CStr` and append a trailing null character. See how string literals are created inside `ash` source.

**Comment by Jerrody** [comment]
> @Jerrody as said don't do that, use `CStr` and append a trailing null character. See how string literals are created inside `ash` source.

Alright, I will change code and will try again.

**Comment by stefnotch** [comment]
@Jerrody Did changing to CStr fix it?

If so, can this issue be closed?

**Comment by Jerrody** [comment]
> @Jerrody Did changing to CStr fix it?
> 
> If so, can this issue be closed?

Yeah.
