### ISSUE TITLE
Convert "unsafe extern "system" fn()" to "unsafe extern "C" fn()"

### ISSUE THREAD

**Issue by vityafx** [ash-rs/ash#767]
So the crate has a type `pub type PFN_vkVoidFunction  = unsafe extern "system" fn()`. The `"system"` part makes it incompatible with `extern "C"` for some reason, and so it is impossible to pass the returned value to any other function which expects it as an argument but as `extern "C"`. Is it possible to change such types (mainly for `get_instance_proc_addr` and `get_device_proc_addr`) from `system` to `C`?

**Comment by Ralith** [comment]
No, that would be incorrect. Vulkan on win32 uses the stdcall ABI, which is what `extern "system"` represents. You must not use `extern "C"` to represent Vulkan function pointers in portable code.

**Comment by Ralith** [comment]
A brief search suggests bindgen supports specifying ABI just fine: https://github.com/rust-lang/rust-bindgen/pull/2329

If not, that's a bindgen problem; you shouldn't use an incorrect ABI definition. If you know you're on Linux where they're equivalent, you can cast the pointers.
