### ISSUE TITLE
Expose a wrapper around AmdBufferMarker

### ISSUE THREAD

**Issue by kvark** [ash-rs/ash#768]
Ideally we'd wrap "VK_AMD_buffer_marker" the same way we wrap other popular extensions, like `khr::DynamicRendering`. In this case, that would be `amd::BufferMarker`. The justification for special attention would be - because this is the recommended way of tooling implementation to deal with GPU crashes on AMD.

**Comment by MarijnS95** [comment]
What kind of "special attention" does this need? Or can I close this issue and move the request to the canonical list of "extension wrapper requests" in #178?

Seems it's only an extension that needs to be loaded and a command to be called.
