### ISSUE TITLE
crates.io version appears to be missing definitions.rs 

### ISSUE THREAD

**Issue by sortofsleepy** [ash-rs/ash#777]
👋

I've been working on a toy renderer and started to do an overhaul over the weekend. It's been awhile since I last updated so I updated Ash to the latest version which, at the time of this writing I believe is `0.37.3+1.3.251`. 

Currently, as least in CLion(my IDE), it reports a bunch of unresolved references including things like `ash::vk::CommandBuffer`, as well as other key components when I grab Ash as a Crate. That being said, things weirdly still appear to build and run without issue so far. 

As far as I can tell the issue has something to do with the code that's on crates.io; if I specify this repository as the source, things appear to be fine and the definitions are found. 

Should I just be pointing to Github from now on? Or is there some other issue on my end I need to look into? (apologies, still a bit new to Rust) 

Thanks!

**Comment by Ralith** [comment]
In general, if CLion generates errors but rustc doesn't, it's a bug in CLion. Using rust-analyzer instead of its built-in Rust support will be more robust.

**Comment by MarijnS95** [comment]
Wouldn't it be surprising if you're [the first of 225.000 downloaders of the `0.37.3` crate](https://crates.io/crates/ash/0.37.3+1.3.251) to report this, while all others silently use the repository source as suggested to work around this?

No, especially if the crate still compiles a critical file cannot just be missing. It must be the IDE messing up, or (though very unlikely) Rust still having the compiled `ash/` crate somewhere in your `target/` folder while the file got deleted or renamed via an accidental hot-key while browsing the source file after a jump-to-symbol.
(I modify files that way by accident from time to time)

The source of the crates.io package can be seen on docs.rs, and it is confirmed to contain `definitions.rs`: https://docs.rs/crate/ash/0.37.3+1.3.251/source/src/vk/definitions.rs

I will close this as it is not an `ash` issue, but you can try to `cargo clean` the project and clear out crate sources from `~/.cargo` to have them redownloaded.

**Comment by sortofsleepy** [comment]
Apologies! I just wasn't sure where to start looking for the problem given how weird it seemed and as I hadn't run into this before.  I had tried completely cleaning and wiping `.cargo` prior to writing which didn't help. Also tried re-installing Rust without success.

Didn't know docs.rs was synced with the crate, will keep that in mind from now on.

I'll open an issue with Jetbrains then, also tried rust-analyser just now like Ralith suggested which also helps confirms things.

Thanks!

**Comment by MarijnS95** [comment]
Did you also try wiping out `~/.cargo` _and `target/`_, after _first shutting down CLion_, and only starting it again after the removal of those folders has completed?

**Comment by sortofsleepy** [comment]
> Did you also try wiping out `~/.cargo` _and `target/`_, after _first shutting down CLion_, and only starting it again after the removal of those folders has completed?

Good point, I actually hadn't tried shutting down CLion + wiping those folders. Unfortunately, just tried now with no luck either. 

Oh well, no worries. I'll just source from Git for the time being or switch to VSCode/rust-analyser until they can fix their plugin.

**Comment by MarijnS95** [comment]
My first guess is that `definitions.rs` comes in at a little over 50k lines now. Perhaps that's too much though it doesn't explain why a `git` revision is fine.

More likely they keep a broken file/compilation cache elsewhere?

**Comment by sortofsleepy** [comment]
That certainly sounds like a possibility. Well hopefully it gets fixed soon.  

Will let you know if they happen to come back to me with anything interesting.
