### ISSUE TITLE
Add VkPhysicalDeviceDynamicRenderingFeatures

### ISSUE THREAD

**Issue by AngelicosPhosphoros** [ash-rs/ash#778]
[Link to spec](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceDynamicRenderingFeatures.html).

It is required to be passed into `DeviceCreateInfo` as `p_next` to be able to use [dynamic rendering](https://lesleylai.info/en/vk-khr-dynamic-rendering/). And that extension is even in core spec now since Vulkan 1.3.

I currently used this workaround:

```rust
            #[repr(C)]
            struct VkPhysicalDeviceDynamicRenderingFeatures {
                sType: vk::StructureType,
                p_next: *const c_void,
                dynamic_rendering: vk::Bool32,
            }

            unsafe impl vk::ExtendsDeviceCreateInfo for VkPhysicalDeviceDynamicRenderingFeatures {}
```

I would also happy to make a PR but it seems that crate code is autogenerated and I don't see where is the source of that generation.

**Comment by MarijnS95** [comment]
This was brought in via a spec update 8 months ago (https://github.com/ash-rs/ash/issues/667) and is already available in the latest released Ash crate(s):

https://docs.rs/ash/latest/ash/vk/struct.PhysicalDeviceDynamicRenderingFeatures.html

(And it implements `ExtendsDeviceCreateInfo`)


Closing as stale :wink:
