### ISSUE TITLE
Default derivation on ImageSubresourceRange struct incorrect

### ISSUE THREAD

**Issue by Exsolutus** [ash-rs/ash#788]
Currently, ImageSubresourceRange simply auto derives the Default trait. 
This causes all of its numeric fields to default to the value `0`. 

However, as seen in the spec for ImageSubresourceRange, `0` is not a valid value for the `level_count` and `layer_count` fields. 
![image](https://github.com/ash-rs/ash/assets/23705866/de185784-7573-4aaf-80e0-dec793cc2091)
The correct default value for these two fields is `1`. 

Additionally, `aspect_mask` should also have a non-zero default value.
![image](https://github.com/ash-rs/ash/assets/23705866/e11c7ac6-ee9e-4901-a4d0-276c4c141da4)
The correct default value here is most likely `COLOR`.

As such, the Default trait should be explicitly implemented to reflect this.

**Comment by Ralith** [comment]
ash's `Default` implementations are not intended to produce values that will be accepted unmodified in Vulkan API calls. This code is working as intended.

**Comment by MarijnS95** [comment]
By the same logic probably 95% of the structs have invalid defaults. The defaults do not exist to help you write shorter code, but to ensure the memory backing the struct is safely initialized to accommodate for our additive builder pattern. It is still up to the author to provide these values themselves (i.e. using struct constructor/update syntax), `ash` is a low-level wrapper and not a validation layer.
