### ISSUE TITLE
Some vulkan device methods may only be provided at an instance level

### ISSUE THREAD

**Issue by EdwinMindcraft** [ash-rs/ash#800]
Some methods in Vulkan may be implemented at the instance level, but not at the driver level.
In my case, using a GTX 1050, the GPU supports the `drawIndirectCount` feature from Vulkan 1.2, but no device implementation seems to be provided for `vkCmdDrawIndirectCount` and `vkCmdDrawIndexedIndirectCount`.
A test allowed me to confirm that those functions do, in fact, exist at the instance level.
As such I wonder if it'd be possible to default device functions to instance functions if the former cannot be found.

**Comment by MarijnS95** [comment]
> A test allowed me to confirm that those functions do, in fact, exist at the instance level.

Did you also confirm that they can be _called_? If the driver does not implement a _device level_ function, how can the dispatch-table generated by the ICD when loading it at the _instance level_ call into such a device function? Are you sure that the extension was properly enabled for the device? Any validation layer errors?

**Comment by EdwinMindcraft** [comment]
Nevermind, I just didn't understand how 1.1+ feature selection worked.
