### ISSUE TITLE
vk::StructureType issue on NVIDIA driver version 545.84

### ISSUE THREAD

**Issue by rfurlan** [ash-rs/ash#801]
Updating to NVIDIA driver version 545.84 leads to the following error and subsequent crash:

`VUID-VkWriteDescriptorSet-pNext-pNext(ERROR / SPEC): msgNum: 1147703268 - Validation Error: [ VUID-VkWriteDescriptorSet-pNext-pNext ] | MessageID = 0x44688fe4 | vkUpdateDescriptorSets: pDescriptorWrites[4].pNext chain includes a structure with unknown VkStructureType (758); Allowed structures are [VkWriteDescriptorSetAccelerationStructureKHR, VkWriteDescriptorSetAccelerationStructureNV, VkWriteDescriptorSetInlineUniformBlock].`

However vk::StructureType does not include the required [VkWriteDescriptorSetAccelerationStructureKHR, VkWriteDescriptorSetAccelerationStructureNV, VkWriteDescriptorSetInlineUniformBlock] types.

**Comment by MarijnS95** [comment]
@rfurlan are you perhaps pushing an object to a `pNext` chain (using `.push_next()` or setting `.p_next` directly) that is subsequently going out of scope, and calling `.build()` on the `VkWriteDescriptorSet` to loose lifetime/borrow information? `758` isn't a valid value: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkStructureType.html

We will fix that in the next breaking release, making it much harder to loose lifetime information (and in turn have dangling pointers) by removing `.build()`. Perhaps you can investigate and/or share the code snippet that is calling into this?

---

Irrespective of that the structures mentioned in the list are all available in the latest release. Note that the `sType` constants _describing these structures_ use `UPPER_SNAKE_CASE`: https://docs.rs/ash/latest/ash/vk/struct.StructureType.html.

https://docs.rs/ash/latest/ash/vk/struct.WriteDescriptorSetAccelerationStructureKHR.html
https://docs.rs/ash/latest/ash/vk/struct.WriteDescriptorSetAccelerationStructureNV.html
https://docs.rs/ash/latest/ash/vk/struct.WriteDescriptorSetInlineUniformBlock.html

(If you look at `impl TaggedStructure` here it denotes the relevant `vk::StructureType` value)

**Comment by rfurlan** [comment]
@MarijnS95 you are absolutely correct, that is what is happening. I got away with it on a previous rustc nightly, now it is time to address it
