### ISSUE TITLE
Missing way to set a builder field in DeviceQueueCreateInfoBuilder

### ISSUE THREAD

**Issue by GummyGun** [ash-rs/ash#832]
There is no way, to set, the `queue_count` directly from the `DeviceQueueCreateInfoBuilder`.
This is just a minor inconvenience since you can just build and set it manually, but it would be nice to get consistency in the methods of this particular struct

**Comment by Ralith** [comment]
It's implied by the length of the slice you pass to `queue_priorities`. This is consistent with every other dynamic array length field.

**Comment by MarijnS95** [comment]
Per [`VUID-VkDeviceQueueCreateInfo-pQueuePriorities-parameter`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDeviceQueueCreateInfo.html#VUID-VkDeviceQueueCreateInfo-pQueuePriorities-parameter)

> pQueuePriorities must be a valid pointer to an array of queueCount float values

This slice is not optional, _and its length must match `queueCount`_. Hence the builder for `queue_priorities()` is the right place to also set `queue_count`.
