### ISSUE TITLE
Errors from latest internal spec with ash-compile CI stage

### ISSUE THREAD

**Issue by oddhack** [ash-rs/ash#836]
@MarijnS95 with the updates to the NV extension merged, we're now getting ash-compile failures in internal gitlab vulkan CI on everything derived from current main branch, AFAICT. Could you take a look at this? Some signature incompatibility seems to be at fault but no idea if that's inconsistent XML or some assumptions ash is making no longer being true. It would be great to fix this in time for the spec update expected on Friday, if possible.

**Comment by MarijnS95** [comment]
Hi @oddhack, I think we discussed this already and ash has to incorporate the spec update and update the handwritten bindings to match, which is done in https://github.com/ash-rs/ash/pull/816.

That is blocking on a recently-discovered usability issue with how Rust tracks "borrows" of the `timings` array, but I think we should resolve that separately.

**Comment by MarijnS95** [comment]
@oddhack it is now merged, shall we re-run some CI jobs?

**Comment by oddhack** [comment]
Seems to work now - thanks!
