### ISSUE TITLE
New builder pattern and push_next with multiple calls

### ISSUE THREAD

**Issue by colinmarc** [ash-rs/ash#844]
I have the following code:

```rust
unsafe fn query_drm_format_modifiers(
    instance: &ash::Instance,
    device: vk::PhysicalDevice,
    format: vk::Format,
) -> Vec<vk::DrmFormatModifierPropertiesEXT> {
    let mut modifiers = vk::DrmFormatModifierPropertiesListEXT::default();
    let mut format_props = vk::FormatProperties2::default().push_next(&mut modifiers);

    instance.get_physical_device_format_properties2(device, format, &mut format_props);

    let mut res = vec![
        vk::DrmFormatModifierPropertiesEXT::default();
        modifiers.drm_format_modifier_count as usize
    ];

    modifiers.p_drm_format_modifier_properties = res.as_mut_ptr();
    instance.get_physical_device_format_properties2(device, format, &mut format_props);

    res
}
```

The [interface](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDrmFormatModifierPropertiesListEXT.html) is a tiny bit weird. The first call returns the number of properties in `modifiers.drm_format_modifier_count`, and the second call fills the array.

The borrow checker doesn't like this:

```rust
error[E0503]: cannot use `modifiers.drm_format_modifier_count` because it was mutably borrowed
  --> mm-server/src/compositor/dma.rs:72:9
   |
66 |     let mut format_props = vk::FormatProperties2::default().push_next(&mut modifiers);
   |                                                                       -------------- `modifiers` is borrowed here
...
72 |         modifiers.drm_format_modifier_count as usize
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of borrowed `modifiers`
...
76 |     instance.get_physical_device_format_properties2(device, format, &mut format_props);
   |                                                                     ----------------- borrow later used here

error[E0506]: cannot assign to `modifiers.p_drm_format_modifier_properties` because it is borrowed
  --> mm-server/src/compositor/dma.rs:75:5
   |
66 |     let mut format_props = vk::FormatProperties2::default().push_next(&mut modifiers);
   |                                                                       -------------- `modifiers.p_drm_format_modifier_properties` is borrowed here
...
75 |     modifiers.p_drm_format_modifier_properties = res.as_mut_ptr();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `modifiers.p_drm_format_modifier_properties` is assigned to here but it was already borrowed
76 |     instance.get_physical_device_format_properties2(device, format, &mut format_props);
   |                                                                     ----------------- borrow later used here
```

One workaround I found was to completely recreate the structs: 

```rust
unsafe fn query_drm_format_modifiers(
    instance: &ash::Instance,
    device: vk::PhysicalDevice,
    format: vk::Format,
) -> Vec<vk::DrmFormatModifierPropertiesEXT> {
    let count = {
        let mut modifiers = vk::DrmFormatModifierPropertiesListEXT::default();
        let mut format_props = vk::FormatProperties2::default().push_next(&mut modifiers);

        instance.get_physical_device_format_properties2(device, format, &mut format_props);
        modifiers.drm_format_modifier_count
    };

    let mut res = vec![vk::DrmFormatModifierPropertiesEXT::default(); count as usize];
    let mut modifiers =
        vk::DrmFormatModifierPropertiesListEXT::default().drm_format_modifier_properties(&mut res);
    let mut format_props = vk::FormatProperties2::default().push_next(&mut modifiers);
    instance.get_physical_device_format_properties2(device, format, &mut format_props);
    
    res
}
```

This feels a little bit clumsy - is there a better way to do this?

**Comment by MarijnS95** [comment]
Because it is a `p_next` structure borrowed by `vk::FormatProperties2`, probably not? The borrow checker is doing its job here, and the only other way around would be using a getter on `format_props.p_next`, but it requires reconstructing what `p_next` points to. We have utilities for that, but they are more relevant for layers where one doesn't have access to the structs up-front on the heap.

---

Your first example could use the builder pattern, as long as the output is reassigned [^1] and it is re-borrowed in a new `vk::FormatProperties2` (closer to the second example):

```rust
modifiers = modifiers.drm_format_modifier_properties(&mut res);
let mut format_props = vk::FormatProperties2::default().push_next(&mut modifiers);
```

[^1]: Because of `Copy` one can easily forget that `modifiers` is copied into the `mut self`, modified inside `drm_format_modifier_properties()` and then moved+`Drop`ped in the return. @Ralith, perhaps we should annotate all our builder functions with `#[must_use]`?

This is resilient against lifetime issues on `res`, i.e. the following won't compile because `modifiers` cannot outlive `res`:

```rust
{
    let mut res = vec![vk::DrmFormatModifierPropertiesEXT::default(); count as usize];
    modifiers = modifiers.drm_format_modifier_properties(&mut res);
}
let mut format_props = vk::FormatProperties2::default().push_next(&mut modifiers);
```

---

While I said you'd have to use a getter on `p_next` to make sure Rust is happy with you mutably accessing `p_next` through `format_props`, it doesn't seem like we actually "thread through" the lifetime of `format_props` when passing its `p_next` pointer through this macro, so the end result is not only horrible to read but also susceptible to mutable aliasing:

```rust
unsafe fn query_drm_format_modifiers(
    instance: &ash::Instance,
    device: vk::PhysicalDevice,
    format: vk::Format,
) -> Vec<vk::DrmFormatModifierPropertiesEXT> {
    let mut modifiers = vk::DrmFormatModifierPropertiesListEXT::default();
    let mut format_props = vk::FormatProperties2::default().push_next(&mut modifiers);

    instance.get_physical_device_format_properties2(device, format, &mut format_props);

    let mut res;
    let p_next = format_props.p_next.cast::<vk::BaseOutStructure<'_>>();
    ash::match_out_struct! {
        // TODO: Why does this not accept an expr?
        match p_next {
            modifiers @ vk::DrmFormatModifierPropertiesListEXT<'_> => {
                let count = modifiers.drm_format_modifier_count;

                res = vec![vk::DrmFormatModifierPropertiesEXT::default(); count as usize];
                *modifiers = (*modifiers).drm_format_modifier_properties(&mut res);
            }
            _ => { panic!() }
        }
    }
    instance.get_physical_device_format_properties2(device, format, &mut format_props);

    res
}
```

**Comment by MarijnS95** [comment]
> You mean how we're able to dereference `p_next` in the `match` block, even though it addresses memory borrowed by `format_props`?

No, it was a note-to-self, while trying to remember if I deliberately chose `$p:ident` over `$p:expr`. Maybe it made `macro_rules!` match fail, maybe because `$p` is referenced multiple times (and we might not want to evaluate the expression more than once, and would have to assign it to a temporary), or maybe because the Rust layer and helper functions I was writing mostly passed around `something: *mut vk::BaseOutStructure` idents.

> I'm guessing that `cast` is throwing away the lifetime.

It's all raw pointers in there, the cast is merely to turn a `*mut c_void` into the `BaseOutStruct` that the macro tries to read.

> Maybe we need `unsafe fn next(&self) -> Option<BaseOutStructure<'_>>` on everything with a `p_next`?

That's preferable, probably:

```rust
unsafe fn next(&self) -> Option<&BaseInStructure<'_>> { NonNull::new... }
unsafe fn next_out(&mut self) -> Option<&mut BaseOutStructure<'_>> { NonNull::new... }
```

And then we don't have to dereference pointers inside the macro either.

> but I think that could be fixed easily enough by generating a helper `fn cast<'a>(x: &BaseOutStructure<'a>) -> Ty<'a> { ... }` rather than using `pointer::cast`.

We might even be able to utilize `Extends*` traits here, `unsafe fn next(_out)<T: ExtendsSelf>(&self) -> Option<&T> {}` style?

**Comment by Ralith** [comment]
> We might even be able to utilize Extends* traits here

I think we'd need a GAT in the trait to let us plug in the right lifetime into `T`, otherwise we're liable to get a `&'a T<'static>`, which would be weird.

I also wonder if we can do this without introducing O(definitions) new code. Something like this gets us started:

```rs
impl<'a> vk::BaseOutStructure<'a> {
    /// Construct a pointer to a `BaseOutStructure` that is outlived by `owner`
    pub fn cast<T: 'a>(owner: &T, ptr: *mut c_void) -> *mut Self {
        _ = owner;
        ptr.cast()
    }
}
```

and perhaps the macro could generate functions with lifetime-preserving casts on demand (e.g. `fn cast<'a>(x: &BaseOutStructure<'a>) -> Option<&DrmFormatModifierPropertiesListEXT<'a>>`).

**Comment by MarijnS95** [comment]
> > perhaps we should annotate all our builder functions with #[must_use]?
> 
> That's an excellent idea.

Done in https://github.com/ash-rs/ash/pull/845!

---

For the rest, I wasn't fully aware that returned mutable pointers are susceptible to lifetimes. Does the suggested `fn cast()` really track that lifetime or does it require us to return an actual borrow instead?

**Comment by i509VCB** [comment]
> I have the following code:
> 
> ```rust
> unsafe fn query_drm_format_modifiers(
>     instance: &ash::Instance,
>     device: vk::PhysicalDevice,
>     format: vk::Format,
> ) -> Vec<vk::DrmFormatModifierPropertiesEXT> {
>     let mut modifiers = vk::DrmFormatModifierPropertiesListEXT::default();
>     let mut format_props = vk::FormatProperties2::default().push_next(&mut modifiers);
> 
>     instance.get_physical_device_format_properties2(device, format, &mut format_props);
> 
>     let mut res = vec![
>         vk::DrmFormatModifierPropertiesEXT::default();
>         modifiers.drm_format_modifier_count as usize
>     ];
> 
>     modifiers.p_drm_format_modifier_properties = res.as_mut_ptr();
>     instance.get_physical_device_format_properties2(device, format, &mut format_props);
> 
>     res
> }
> ```
> 
> The [interface](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDrmFormatModifierPropertiesListEXT.html) is a tiny bit weird. The first call returns the number of properties in `modifiers.drm_format_modifier_count`, and the second call fills the array.
> 
> The borrow checker doesn't like this:
> 
> ```rust
> error[E0503]: cannot use `modifiers.drm_format_modifier_count` because it was mutably borrowed
>   --> mm-server/src/compositor/dma.rs:72:9
>    |
> 66 |     let mut format_props = vk::FormatProperties2::default().push_next(&mut modifiers);
>    |                                                                       -------------- `modifiers` is borrowed here
> ...
> 72 |         modifiers.drm_format_modifier_count as usize
>    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of borrowed `modifiers`
> ...
> 76 |     instance.get_physical_device_format_properties2(device, format, &mut format_props);
>    |                                                                     ----------------- borrow later used here
> 
> error[E0506]: cannot assign to `modifiers.p_drm_format_modifier_properties` because it is borrowed
>   --> mm-server/src/compositor/dma.rs:75:5
>    |
> 66 |     let mut format_props = vk::FormatProperties2::default().push_next(&mut modifiers);
>    |                                                                       -------------- `modifiers.p_drm_format_modifier_properties` is borrowed here
> ...
> 75 |     modifiers.p_drm_format_modifier_properties = res.as_mut_ptr();
>    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `modifiers.p_drm_format_modifier_properties` is assigned to here but it was already borrowed
> 76 |     instance.get_physical_device_format_properties2(device, format, &mut format_props);
>    |                                                                     ----------------- borrow later used here
> ```
> 
> One workaround I found was to completely recreate the structs:
> 
> ```rust
> unsafe fn query_drm_format_modifiers(
>     instance: &ash::Instance,
>     device: vk::PhysicalDevice,
>     format: vk::Format,
> ) -> Vec<vk::DrmFormatModifierPropertiesEXT> {
>     let count = {
>         let mut modifiers = vk::DrmFormatModifierPropertiesListEXT::default();
>         let mut format_props = vk::FormatProperties2::default().push_next(&mut modifiers);
> 
>         instance.get_physical_device_format_properties2(device, format, &mut format_props);
>         modifiers.drm_format_modifier_count
>     };
> 
>     let mut res = vec![vk::DrmFormatModifierPropertiesEXT::default(); count as usize];
>     let mut modifiers =
>         vk::DrmFormatModifierPropertiesListEXT::default().drm_format_modifier_properties(&mut res);
>     let mut format_props = vk::FormatProperties2::default().push_next(&mut modifiers);
>     instance.get_physical_device_format_properties2(device, format, &mut format_props);
>     
>     res
> }
> ```
> 
> This feels a little bit clumsy - is there a better way to do this?

VK_EXT_image_drm_format_modifier is a bit weird as it is the only case I know of doing this type of query and write thing on a pointer chain.

I believe you can just insert a `drop(format_props)` to release the borrow on modifiers, then just make a new format_props. It isn't ideal but it has worked in my experience.

**Comment by MarijnS95** [comment]
@i509VCB friendly request to _not copy/quote the entire OP_ - sample code and all - when only replying to a tiny portion of it, or to the entire issue context as a whole. It makes notification reading unnecessarily troublesome :wink: 

---

`drop()` is not even needed if you just refrain from using `format_props` further down the line, as already shown above. `vk::FormatProperties2` needs to be recreated and `drop()` does not solve that.

**Comment by MarijnS95** [comment]
Looks like we have proposed enough alternatives to make this work, closing.
