### ISSUE TITLE
vulkan gitlab CI failing with wrong rustc version

### ISSUE THREAD

**Issue by oddhack** [ash-rs/ash#847]
See any of the recent ash-compile steps in gitlab internal CI - they all are failing with

> error: package `ash v0.37.0+1.3.271 (/builds/vulkan/vulkan/ash)` cannot be built because it requires rustc 1.69.0 or newer, while the currently active rustc version is 1.68.0

Probably because the Docker image containing rust is now out of date with the underlying project? If so I think you could regenerate and push https://github.com/KhronosGroup/DockerContainers/blob/main/rust.Dockerfile, then just need to update the container SHA256 in gitlab and perhaps github CI scripts.

**Comment by MarijnS95** [comment]
Correct, we recently bumped our MSRV to #746, and the current CI image predates that release.
