### ISSUE TITLE
Std* video params need to be on the heap, not references

### ISSUE THREAD

**Issue by colinmarc** [ash-rs/ash#849]
I'm not sure if this is actually an ash bug per se, but at best the lifetime information on the following is misleading:

```
impl<'a> VideoEncodeH264SessionParametersAddInfoEXT<'a> {
    #[inline]
    pub fn std_sp_ss(mut self, std_sp_ss: &'a [StdVideoH264SequenceParameterSet]) -> Self {
        self.std_sps_count = std_sp_ss.len() as _;
        self.p_std_sp_ss = std_sp_ss.as_ptr();
        self
    }
    #[inline]
    pub fn std_pp_ss(mut self, std_pp_ss: &'a [StdVideoH264PictureParameterSet]) -> Self {
        self.std_pps_count = std_pp_ss.len() as _;
        self.p_std_pp_ss = std_pp_ss.as_ptr();
        self
    }
}
```
(The snake_casing is also weird.)

That's because the `[StdVideoH264SequenceParameterSet]` pointer actually needs to be on the heap, and outlive the call that uses this struct (to `vkCreateVideoSessionParametersKHR`).

I don't know what's involved in that, since this seems to be generated code, and I'm not sure how to indicate in the API that the pointer needs to be a heap pointer anyway. Feel free to close if I'm misunderstanding the issue.

**Comment by Ralith** [comment]
You can address heap memory with that just fine. What is the actual problem you're having?

**Comment by colinmarc** [comment]
I tripped over it because the bindings don't indicate that that parameter is any different (the lifetime matches the parent struct), and mesa segfaulted (in a completely different part of the program). I figured it out eventually, but I was wondering if ash and the borrow checker could've caught the bug for me, since it seems like a lifetime problem. I understand that the borrow checker can't peer into the C code, but maybe there's another way?

I ended up doing the following:

```
struct Headers264 {
    sps: StdVideoH264SequenceParameterSet,
    sps_vui: StdVideoH264SequenceParameterSetVui,
}

impl Headers264 {
    unsafe fn new(width: u32, height: u32, profile_idc: u32) -> Pin<Box<Self>> {
   
        let vui = StdVideoH264SequenceParameterSetVui {
            // <snip>
        };

        let mut sps = StdVideoH264SequenceParameterSet {
            // <snip>
        };

        let headers = Box::pin(Self {
            sps,
            sps_vui: vui,
        });

        sps.pSequenceParameterSetVui = <*const _>::cast(&headers.sps_vui);

        headers
    }
```

So maybe the parameter should require a `Pin`? I'm pretty new to rust, so I have no idea whether that's idiomatic.

**Comment by MarijnS95** [comment]
Oh never mind, I thought your sample was incomplete but you are merely storing the objects. In that case _you_ are responsible for the lifetime of any references that it points to.

In newer ash versions (use the `master` branch until it is released) this pattern will be made much harder, but you might be able to get it to work with a self-referential pinned struct.

**Comment by colinmarc** [comment]
Sorry, it was indeed incomplete - I then call `CreateSessionParameters` with the pinned struct this way:

```rust
let mut h264_add_info = vk::VideoEncodeH264SessionParametersAddInfoEXT::default();

// I could also store a slice in my pinned struct, but this works too.
h264_add_info.p_std_sp_ss = <*const _>::cast(&headers_264.sps);
h264_add_info.std_sps_count = 1;

let mut h264_info = vk::VideoEncodeH264SessionParametersCreateInfoEXT::default()
    .parameters_add_info(&h264_add_info);

let mut create_info =
    vk::VideoSessionParametersCreateInfoKHR::default().video_session(session).push_next(&mut h264_info);

unsafe {
    video_loader
        .create_video_session_parameters(&create_info, None)
        .context("vkCreateVideoSessionParametersKHR")?
}
```

I can tell it's uncommon because I've written a boatload of ash code in the past few weeks and this is the first time I've run into this. However, it does indeed seem to be required, afaict from the driver code and spec.

**Comment by MarijnS95** [comment]
Can you link the spec that states this? Unless there's a good reason such behaviour should probably be reported upstream.

**Comment by Ralith** [comment]
If your driver is trying to access application pointers from outside of the Vulkan call in which the pointer occurred, that's a driver bug. Outside of a few rare cases involving importing platform-specific shared memory, Vulkan never stores pointers to application memory.

Please don't mistake driver bugs for spec requirements.

**Comment by colinmarc** [comment]
It sounds like I misunderstood what was going on here, sorry for the trouble.

**Comment by MarijnS95** [comment]
@colinmarc mind sharing what the misunderstanding and solution was, so that future readers are helped as well?
