### ISSUE TITLE
Any reason for not having descriptorIndexing extension not having it's own type?

### ISSUE THREAD

**Issue by GummyGun** [ash-rs/ash#856]
I would like to know if there is any reason in particular to not having this implemented descriptorIndexing. 
I know that, ExtDescriptorIndexingFn exists but I am curious about this is it because it is a newer extension? 
This small change will help keep the interface consistant.

**Comment by Ralith** [comment]
What extension do you think is missing? "descriptorIndexing" is not the name of a Vulkan extension. `VK_EXT_descriptor_indexing` is, and it has a struct.

**Comment by GummyGun** [comment]
I was referring to about a struct inside the `ash::extensions::ext` module, maybe it would be kind of a small struct since there are no associated functions to the extension that would require the instantiation of the struct but you could at least call `ash::extensions::ext::DescriptorIndexing::name()`

**Comment by Ralith** [comment]
Again, which extension do think is missing a struct? What is its name?

**Comment by MarijnS95** [comment]
The consistency is that extensions without functions do not have a hand-written extension wrapper in `ash::extensions::<vendor>::<extname>`. You can always use `vk::ExtDescriptorIndexingFn::name()` instead.

Maybe this might change when the layout of extensions, functions and wrappers is restructured in the bindings.

**Comment by MarijnS95** [comment]
We've refactored the layout of extension modules completely in #894, in the next release all names will be available under `ash::<prefix>::<extension name>::NAME` regardless of the existence of a hand-written high-level helper.
