### ISSUE TITLE
ash builder pattern is error prone

### ISSUE THREAD

**Issue by yshui** [ash-rs/ash#866]
Many of the builder methods take references with lifetime, such as [DeviceCreateInfoBuilder::queue_create_infos](https://docs.rs/ash/latest/ash/vk/struct.DeviceCreateInfoBuilder.html#method.queue_create_infos), but have a final `.build()` which returns something without a lifetime. This leads me to believe falsely the returned struct holds a copy of the passed arguments internally, thus not limited by the source lifetime. But this is not the case, ash converts the passed references to pointers, which means the passed arguments must _**live longer**_ than the returned value.

_No where_ in documentation was this mentioned. And the API is designed in such a way that makes leveraging the borrow checker impossible. I suggest the return from builders should retain the lifetime of the builder.

**Comment by yshui** [comment]
Real example of misuse: vulkano-rs/vulkano#2465

**Comment by Friz64** [comment]
This has been fixed by #602, and will be released in a future version.

**Comment by Ralith** [comment]
It is also warned against in the API docs for every single `build` method.

**Comment by yshui** [comment]
darn I was a bit late then :sweat_smile: feel free to close it now or when the change is released.

**Comment by MarijnS95** [comment]
@tomaka what is wrong about that example? The slice has a `'static` lifetime, so it is sound to return a `ash::vk::SubpassDescription` with a pointer to that ever-lasting slice.

**Comment by Ralith** [comment]
In your example, the array literal is getting promoted to having a static lifetime. Try using a dynamic value in it to prevent this, and observe that it will no longer compile.
