### ISSUE TITLE
Do you use the feature number= XML attribute?

### ISSUE THREAD

**Issue by oddhack** [ash-rs/ash#873]
@MarijnS95 I'm thinking about replacing the \<feature number="1.x"> attribute in the XML with an explicit \<feature depends="dependency expression"> attribute instead, as people are using the 'number' to infer information it isn't intended to provide(*). Do you make any use of the 'number' attribute in Ash?

(*) Literally all we intended it for was to established a fixed order in which feature tags are emitted by our generator scripts. The specific numeric value is irrelevant to this.

**Comment by MarijnS95** [comment]
@oddhack it seems ash uses these to separate out to which Vulkan version functions belong, so that we can generate per-version function-pointer-loader-structs. This is mostly oblivious to the user though.

**Comment by MarijnS95** [comment]
For completeness, the `vk-parse` (CC @krolli) crate that we use under the hood [currently requires `number` to be set](https://github.com/krolli/vk-parse/blob/11f1a1f44e9462cb4c610d9a01b6e2e9793d8c11/vk-parse/src/parse.rs#L958). That should be relaxed to an `Option` and `depends` should be added when this `vk.xml` change is pushed ahead.

I don't think Ash's generator is otherwise using the `.number` field.

**Comment by oddhack** [comment]
> For completeness, the `vk-parse` (CC @krolli) crate that we use under the hood [currently requires `number` to be set](https://github.com/krolli/vk-parse/blob/11f1a1f44e9462cb4c610d9a01b6e2e9793d8c11/vk-parse/src/parse.rs#L958). That should be relaxed to an `Option` and `depends` should be added when this `vk.xml` change is pushed ahead.

This change has been published in Vulkan-Docs for a while now, so you may want to go ahead with this change if you have not already.

**Comment by MarijnS95** [comment]
@oddhack it looks like @krolli fixed this in June at https://github.com/krolli/vk-parse/commit/10bac24f7e953b0def4d386c7ab369762ad4e812 :+1:. Looks like we can close this now, `number` is optional and `depends` was added as a new field. Neither are used by Ash at the moment.
