### ISSUE TITLE
Use linked by default

### ISSUE THREAD

**Issue by liferooter** [ash-rs/ash#903]
Use `dlopen` is usually a bad idea that makes it harder to track the binary dependencies and makes packaging harder sometimes (e.g. in case of Nix, where dependencies can be automatically derived from dynamic linkage) and gives no advantages unless the application somehow specially handles the case of non-existing Vulkan, which is usually not the case. So I think it makes sense to make `linked` the default instead of `loaded`.

**Comment by MarijnS95** [comment]
I can think of a lot of apps and games that like to fall back to GL or DirectX. Though not having a Vulkan driver is becoming way less common.

Users are still free to change the default, or we should remove the default altogether to not have utility crates accidentally force either mode (most likely: the one that is the default, with `linked` being more harmful) if they forget `default-features = false` etiquette.

**Comment by Ralith** [comment]
`loaded` can also be nice for e.g. Windows CI, where extra effort is required to get libvulkan. I use `linked` in my projects but I'm not sure it's the friendliest default.

**Comment by liferooter** [comment]
Okay, see your points, thank you
