### ISSUE TITLE
how to get PhysicalDeviceProperties

### ISSUE THREAD

**Issue by float3** [ash-rs/ash#908]
i checked https://docs.rs/ash/latest/ash/?search=PhysicalDeviceDriverProperties

in cpp it would look like this
```cpp
	const auto DevicePropertyChain = PhysicalDevice.getProperties2<
		vk::PhysicalDeviceProperties2, vk::PhysicalDeviceDriverProperties>();

	const auto& DeviceProperties
		= DevicePropertyChain.get<vk::PhysicalDeviceProperties2>();
	const auto& DeviceDriverProperties
		= DevicePropertyChain.get<vk::PhysicalDeviceDriverProperties>();
```

I found some rust code snippets that use a `builder()` like so

```rs
        // Query additional properties
        let mut driver_properties = vk::PhysicalDeviceDriverProperties::default();
        let mut properties2 = vk::PhysicalDeviceProperties2::builder()
            .push_next(&mut driver_properties)
            .build();
        unsafe {
            device
                .instance()
                .get_physical_device_properties2(device.physical_device().raw(), &mut properties2);
        }
        let properties = device.physical_device().properties();
```

but it doesn't seem to exit,
I can't find it on here
https://docs.rs/ash/latest/ash/vk/struct.PhysicalDeviceProperties2.html

**Comment by zedrian** [comment]
Hello @float3,
The builder pattern was removed in Ash 0.38 - all structures are now created directly instead.
So the snippet you showed might be changed to something like this:
```rust
let mut driver_properties = vk::PhysicalDeviceDriverProperties::default();
let mut properties2 = vk::PhysicalDeviceProperties2::default()
    .push_next(&mut driver_properties);
unsafe {
    device
        .instance()
        .get_physical_device_properties2(device.physical_device().raw(), &mut properties2);
}
```

**Comment by float3** [comment]
hmm i did this which should be equivalent to your snippet but all the fields or empty like they were just initialized to default values

```rs
    pub fn new(instance: &Instance, physical_device: vk::PhysicalDevice) -> Self {
        let physical_device_properties =
            unsafe { instance.get_physical_device_properties(physical_device) };

        let mut driver_properties = vk::PhysicalDeviceDriverProperties::default();

        let mut properties2 =
            vk::PhysicalDeviceProperties2::default().push_next(&mut driver_properties);

        unsafe {
            instance.get_physical_device_properties2(physical_device, &mut properties2);
        }
```

**Comment by float3** [comment]
also trying to figure out how to get this [PhysicalDeviceShaderSMBuiltinsPropertiesNV](https://docs.rs/ash/latest/ash/vk/struct.PhysicalDeviceShaderSMBuiltinsPropertiesNV.html#)

**Comment by MarijnS95** [comment]
@float3 This appears to be confusing. `VK_KHR_get_physical_device_properties2` (the extension needed to call `get_physical_device_properties2()`) has only been stabilized in Vulkan 1.1, yet on at least `radv` the function seems to load correctly on `api_version` set to `1.0.0` _without_ enabling the extension.

None of the `pNext` pointers are initialized however, and the Validation Layer is rather unhelpful:

```
VALIDATION [VUID-VkPhysicalDeviceProperties2-pNext-pNext (-579609649)] : Validation Error: [ VUID-VkPhysicalDeviceProperties2-pNext-pNext ] Object 0: handle = 0x55c71d2788c0, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xdd73dbcf | vkGetPhysicalDeviceProperties2(): pProperties->pNext includes a pointer to a VkStructureType (VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DRIVER_PROPERTIES), but its parent extension VK_KHR_driver_properties has not been enabled. The Vulkan spec states: Each pNext member of any structure (including this one) in the pNext chain must be either NULL or a pointer to a valid struct for extending VkPhysicalDeviceProperties2 (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPhysicalDeviceProperties2-pNext-pNext)
```

This is a device extension, so enabling it on the instance will likely get you into `ERROR_EXTENSION_NOT_PRESENT` territory. Once you set your `api_version` to at least `1.1` or enable `VK_KHR_get_physical_device_properties2`, you should be able to load these `PhysicalDevice**Properties`. Same for `VkPhysicalDeviceShaderSMBuiltinsPropertiesNV`.

**Comment by float3** [comment]
could you show me how to do that with ash? I'm unable to figure it out just using the docs

**Comment by MarijnS95** [comment]
@float3 note that this is general Vulkan usage that also translates C++. It isn't specific to Rust nor `ash`.
