### ISSUE TITLE
Document the meaning of `bool` return values

### ISSUE THREAD

**Issue by dthusian** [ash-rs/ash#928]
The C signature of `vkGetFenceStatus` is the following (from the spec):
```c
// Provided by VK_VERSION_1_0
VkResult vkGetFenceStatus(
    VkDevice                                    device,
    VkFence                                     fence);
```

The Rust signature of `ash::Device::get_fence_status` is the following:
```rust
pub unsafe fn get_fence_status(&self, fence: Fence) -> VkResult<bool>
```

It's not obvious how the `VkResult` return value is converted into a `bool`, especially because the spec also defines the following for `VkResult`:
```c
// Provided by VK_VERSION_1_0
typedef enum VkResult {
    VK_SUCCESS = 0,
    VK_NOT_READY = 1,
...
```

Someone might expect that the VkResult is just casted into a bool, with non-zero values converted to `true`, and zero values converted to `false`. However, this is contrary to the behavior of the function, which makes `VK_SUCCESS` map to `true` and `VK_NOT_READY` map to `false`.

This behavior should be documented on Vulkan functions that return `bool`s in Rust but not in C to avoid confusion.

**Comment by MarijnS95** [comment]
This function has very clearly defined return values:

https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetFenceStatus.html

**Comment by Ralith** [comment]
I think the point is that ash's wrapper diverges from that documentation enough to be unclear.

**Comment by MarijnS95** [comment]
Sure, we could always describe that since we have more control over the return type, we map NOT_READY to _not_ be part of Err(x) but Ok(false) instead. Perhaps make this a PR instead?

**Comment by MarijnS95** [comment]
@dthusian I've opened https://github.com/ash-rs/ash/pull/929, please review and see whether that is to your liking.

---

Just in case @dthusian I'd like to know how you got to this:

> Someone might expect that the VkResult is just casted into a bool, with non-zero values converted to `true`, and zero values converted to `false`.

The returned `bool` is _wrapped inside a `VkResult<>`_. If the underlying `vk::Result` value is casted to a `bool`, what would we use to fill `VkResult<>` with then? Never return `Err(err_code)` but always `Ok(err_code as bool)`?

Understanding your thoughts and expectations here is critical for us to improve the function signatures and documentation.

**Comment by dthusian** [comment]
> The returned `bool` is wrapped inside a `VkResult<>`. If the underlying `vk::Result` value is casted to a `bool`, what would we use to fill `VkResult<>` with then? Never return `Err(err_code)` but always `Ok(err_code as bool)`?

I thought it might be that any non-`SUCCESS` non-`NOT_READY` value maps to `Err`, otherwise, it is casted. In any case, the PR looks to me, thank you.
