### ISSUE TITLE
require / feature tag causing Vulkan-Docs CI failures for Ash generation

### ISSUE THREAD

**Issue by oddhack** [ash-rs/ash#937]
We recently added a 'feature' tag inside 'require' tags to help autogenerate some spec and CTS code, and this is causing failures in Vulkan-Docs Rust bindings generation, see e.g. https://github.com/KhronosGroup/Vulkan-Docs/actions/runs/10630741404/job/29505301539 .

**Comment by oddhack** [comment]
Note this is unrelated to the top-level 'feature' tag used to describe core API versions; it is an unfortunate name overload.

**Comment by MarijnS95** [comment]
We were already tracking the necessary changes in https://github.com/krolli/vk-parse/pull/33 and https://github.com/ash-rs/ash/pull/910#issuecomment-2321080696, but I've separated that change out for now to push it straight to master.
