### ISSUE TITLE
Should enums implement fmt::Display?

### ISSUE THREAD

**Issue by coffeenotfound** [ash-rs/ash#938]
It would be nice if there was a quick way to print various vulkan enums to a proper string.
I'm not aware that such functionality exists in ash right now

Implementing fmt::Display for each enum would be pretty nice.
Has this been considered yet? Are there downsides? (Binary overhead of 10 gazillion strings?)

**Comment by MarijnS95** [comment]
@coffeenotfound is https://github.com/ash-rs/ash/blob/master/ash/src/vk/const_debugs.rs what you are looking ofr?

**Comment by coffeenotfound** [comment]
Yeah, that's exactly what I was looking for 🤦
Thanks for the pointer :D
