### ISSUE TITLE
#BUG PhysicalDeviceFeatures2 not initializing values even when passed with defautl() initialized structs

### ISSUE THREAD

**Issue by DeCedDNA** [ash-rs/ash#948]
When you create a PDF2 (PhysicalDeviceFeatures2) like this:
![image](https://github.com/user-attachments/assets/331e17cb-a2d3-456c-8659-a79d3daa0312)

this error message appears:
![image](https://github.com/user-attachments/assets/20499200-4757-4cc7-b32e-bbcc1bd15421)

NOTE: Every variable you see just has their default() impl of the struct and on device create level I passed the returned PDF2 in the p_next:
![image](https://github.com/user-attachments/assets/0cf9274e-a2f9-4474-959f-3572a85595b2)

But now when I uncomment the code where physical_device_features2 ONLY holds (and NEVER uses) a default() init of PDF2 everything works just fine. I am not sure how exactly things work in the background but that does not seem right.

**Comment by Ralith** [comment]
You are returning a pointer to stack-allocated memory in `p_next`. Use the setters to avoid this mistake.
