### ISSUE TITLE
ash shouldn't require a lifetime for raw C ffi types

### ISSUE THREAD

**Issue by maia-s** [ash-rs/ash#956]
As far as I've been able to find out, `ash::vk` is the closest we get to a sys crate for Vulkan in rust, so I just added support to the `sdl3-sys` crate in git for optionally using Vulkan types from `ash::vk`. However, the `vk::AllocationCallbacks` type requires a lifetime, and this being C ffi, there's no way for me to set a correct lifetime for it. I've aliased it to use `'static` for now, but this shouldn't have a lifetime.

**Comment by Ralith** [comment]
Lifetimes are optional, and it sounds like you worked that out.
