### ISSUE TITLE
Segmentation Fault on Linux (Wayland) When Destroying Swapchain

### ISSUE THREAD

**Issue by FedericoCapoccia** [ash-rs/ash#957]
This is the repo in question: https://github.com/FedericoCapoccia/minecrust
### Description:
On <b>Windows</b>, the application runs perfectly without any validation errors.
However, on <b>Linux (Wayland)</b>, I encounter a segmentation fault after closing the window.
Using a debugger, I traced the issue to the following line of code:

```rust
// renderer/src/core/swapchain.rs, line 165
unsafe { self.loader.destroy_swapchain(self.handle, None) };
```
where ```loader``` is the ```ash::khr::swapchain::Device``` from which the swapchain was created.

### Details:
- <b>During rendering</b>, the swapchain creation and destruction seem to be handled correctly, I've confirmed this because swapchain recreation on window resizing works without any validation error.
- The segmentation fault only occurs on the final cleanup after closing the winow.
- Skipping swapchain destruction during final cleanup leads to numerous validation errors, so it’s clear that cleanup is necessary, but something is going wrong during this process.
- On Windows, this issue does not occur.
- Ruinning a [similar program](https://github.com/FedericoCapoccia/LearnVulkan) written in C++, from which this project is heavily inspired from, does not cause any error. This suggests the problem might be specific to the Rust/ash implementation or Vulkan/Wayland interaction.

### Question:
Could this be:
- A mistake in my implementation?
- A driver-related issue on Linux?
- An edge case or bug within ash itself?

### System Spec:
- OS: Linux
- Distro: Archlinux
- Mesa version: Mesa 24.2.5-arch1.1
- Vulkan Instance Version: 1.3.295
- Device name: AMD Radeon RX 6800 XT (RADV NAVI21)

**Comment by Friz64** [comment]
This is a bug in your implementation, the other two can easily be ruled out by running any correct ash program.

Your bug is very likely caused by incorrect destruction order. What I suspect will fix it is swapping these two lines:

https://github.com/FedericoCapoccia/minecrust/blob/master/sandbox%2Fsrc%2Fapp.rs#L10-L11

This is because Rust structs drop their fields top to bottom, which means your Window gets destroyed before your Renderer, and thus your swapchain, does.

**Comment by FedericoCapoccia** [comment]
Yeah now I feel like a dumbass, thank you and keep up the good work
