### ISSUE TITLE
Ignoring unrecognized attributes (redux)

### ISSUE THREAD

**Issue by oddhack** [ash-rs/ash#959]
We are getting this ash-generate CI error in the internal vulkan spec repo again (see e.g. https://gitlab.khronos.org/vulkan/vulkan/-/jobs/658141), which spreads out to affect more branches as people sync up their working branches to main. They are just warnings, but unfortunate when they result in every CI job coming up with the warning label.

@MarijnS95 could you remind me where you are WRT ignoring unrecognized attributes? If not addressed this is going to keep happening as we do come up with new attributes reasonably often to convey more semantic information about API entities.

**Comment by MarijnS95** [comment]
> where you are WRT ignoring unrecognized attributes?

I initially went the inverse and made this a hard error in August, as we were previously ignoring it entirely which made it hard to backtrack errors: https://github.com/ash-rs/ash/pull/930

As this is causing so many issues in upstream CI, I'll demote this to a more screaming error that is not actually aborting our process.

**Comment by MarijnS95** [comment]
After merging and re-running the CI code generation is once again successful, but compiling still fails because of https://github.com/ash-rs/ash/issues/343#issuecomment-2396499207 / #952, which I hope to fix with #951.

**Comment by oddhack** [comment]
@MarijnS95 this seems to be taking quite a while, and I'm inclined to remove ash from the Vulkan spec repo CI until it's resolved - it's not doing any good to raise warnings in every branch for reasons outside the spec repo itself, and it's causing some confusion with Vulkan-Hpp as those project owners keep checking the CI logs to see if the CI warning is coming from their binding or not. The idea was to detect problems with the language bindings before publishing spec updates but it is not fulfilling that purpose, at present.

**Comment by MarijnS95** [comment]
@oddhack yes please, I've been thinking about doing the same thing. Don't forget to remove it from both GitHub and GitLab.
