### ISSUE TITLE
VkDescriptorSetLayoutCreateFlagBits are missing in bitflags.rs

### ISSUE THREAD

**Issue by aemreaydin** [ash-rs/ash#961]
The DescriptorSetLayoutCreateFlags is currently empty. It should implement all the flags from the [VulkanDocs](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDescriptorSetLayoutCreateFlagBits.html) to ensure it matches the Vulkan specification.

**Comment by aemreaydin** [comment]
Hopefully I'm not missing anything about this, if it is in fact missing, I'm willing to work on it as I need the functionality anyways.

**Comment by Friz64** [comment]
Why do you think it's empty? The flags are right there. https://docs.rs/ash/latest/ash/vk/struct.DescriptorSetLayoutCreateFlags.html#impl-DescriptorSetLayoutCreateFlags-1

**Comment by MarijnS95** [comment]
`DescriptorSetLayoutCreateFlags ` is a newtype struct. Only one of the `impl` blocks, which is the one for baseline Vulkan 1.0, is empty:

https://docs.rs/ash/0.38.0/src/ash/vk/bitflags.rs.html#691

The first values are defined by extensions, and by Vulkan 1.2:

https://docs.rs/ash/0.38.0/src/ash/vk/feature_extensions.rs.html#221-224

The end result, as @Friz64 showed, is a build-up of many flags cobbled together from many features/extensions in the documentation.

**Comment by aemreaydin** [comment]
Ah, sorry about that.
Thanks for the clarification.
