### ISSUE TITLE
VK_WHOLE_SIZE missing?

### ISSUE THREAD

**Issue by Firestar99** [ash-rs/ash#963]
Ash does not seem to expose `VK_WHOLE_SIZE` at all. Is there a specific reason why it is not available? 

> VK_WHOLE_SIZE is a special value indicating that the entire remaining length of a buffer following a given offset should be used. It can be specified for [VkBufferMemoryBarrier](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkBufferMemoryBarrier.html)::size and other structures.
> `#define VK_WHOLE_SIZE                     (~0ULL)`

https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_WHOLE_SIZE.html

**Comment by MarijnS95** [comment]
But it exists? https://docs.rs/ash/latest/ash/vk/constant.WHOLE_SIZE.html

You can even find it when searching for the entire `VK_`-prefixed symbol in the documentation, despite us not having `doc(alias)` yet: https://docs.rs/ash/latest/ash/vk/constant.WHOLE_SIZE.html?search=vk_whole_size

**Comment by Firestar99** [comment]
Thanks! Somehow I missed that. Seems to also be the only constant you'd commonly need.
