### ISSUE TITLE
macOS env vars don't work in .cargo/config.toml

### ISSUE THREAD

**Issue by rnikander** [ash-rs/ash#973]
The Readme has a section [here](https://github.com/ash-rs/ash?tab=readme-ov-file#macos) that says we need to set environment vars on macOS:

```
VULKAN_SDK=$HOME/VulkanSDK/<version>/macOS \
DYLD_FALLBACK_LIBRARY_PATH=$VULKAN_SDK/lib \
VK_ICD_FILENAMES=$VULKAN_SDK/share/vulkan/icd.d/MoltenVK_icd.json \
VK_LAYER_PATH=$VULKAN_SDK/share/vulkan/explicit_layer.d \
```

That works when I do it from the shell, but if I set them in `.cargo/config.toml`, and I try running the triangle example, I see an error like:

```
dyld[27353]: Library not loaded: @rpath/libvulkan.1.dylib
  Referenced from: <1C30336C-0A98-389F-AAF0-7CBD59D51D72> /Users/rob/Workspace/ThirdParty/ash/target/debug/triangle
  Reason: tried: 
'/Users/rob/Workspace/ThirdParty/ash/target/debug/deps/libvulkan.1.dylib' (no such file), 
'/Users/rob/Workspace/ThirdParty/ash/target/debug/libvulkan.1.dylib' (no such file), 
'/Users/rob/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libvulkan.1.dylib' (no such file), 
'/Users/rob/.rustup/toolchains/stable-x86_64-apple-darwin/lib/libvulkan.1.dylib' (no such file), 
'/Users/rob/lib/libvulkan.1.dylib' (no such file), 
'/usr/local/lib/libvulkan.1.dylib' (no such file), 
'/usr/lib/libvulkan.1.dylib' (no such file, not in dyld cache)
```

Shouldn't the env vars in Cargo's config work the same as those set in the shell? I prefer to set them in Cargo's config, because shells are different on different platforms. 
 
Here's my `.cargo/config.toml`:
```
[env]
VULKAN_SDK = "/Users/rob/Dev/VulkanSDK/1.3.275.0/macOS"
DYLD_FALLBACK_LIBRARY_PATH = "/Users/rob/Dev/VulkanSDK/1.3.275.0/macOS/lib"
VK_ICD_FILENAMES = "/Users/rob/Dev/VulkanSDK/1.3.275.0/macOS/share/vulkan/icd.d/MoltenVK_icd.json"
VK_LAYER_PATH = "/Users/rob/Dev/VulkanSDK/1.3.275.0/macOS/share/vulkan/explicit_layer.d"
```

**Comment by Ralith** [comment]
How, exactly, did you try running the example?

This is not an ash issue, but we might be able to help you work out what's wrong with your workflow.

**Comment by rnikander** [comment]
> How, exactly, did you try running the example?

I first tried within my IDE (IntelliJ + rust plugin). But same thing happens from command line: `cargo run -p ash-examples --bin triangle`

**Comment by Ralith** [comment]
My guess would be that `DYLD_FALLBACK_LIBRARY_PATH` must be set in the environment in which cargo (and/or your IDE, if your IDE doesn't just invoke cargo) runs, since cargo is what's invoking spawning the process. You may be able to find more info by reviewing the documentation or implementation of your OS's dynamic loader. Alternatively, you could avoid using the `linked` feature, so that the libvulkan search will happen definitely inside the new process, after it's launched.

**Comment by rnikander** [comment]
Okay, thanks. I may report this as a cargo issue and see if they think `[env]` is supposed to work exactly like environment variables or not. 

I guess for a dev environment I can do a load instead of "linked", but I'm trying to make an app to distribute, so eventually it seems I'll have to figure out how to link it into one file. It's confusing on macOS because there are .a files in there for the "libMoltonVK" but not "libvulkan". 

Anyway, thanks.

**Comment by Ralith** [comment]
The Vulkan loader (libvulkan) is not designed to be statically linked. If you distribute on macOS, you can probably package everything into a bundle without needing a monolithic binary. I think it is possible to statically link MoltenVK directly if you really want but you'll probably need to review upstream docs to work out the specifics.
