### ISSUE TITLE
It seems to me or in ash >= 0.38, not all instance extensions can be obtained

### ISSUE THREAD

**Issue by olejaaaaaaaa** [ash-rs/ash#975]
I get all instance layers but not all extensions like VK_KHR_win32_surface. I'm new to vulkan ash, so I don't understand, am I doing something wrong?

```rust
    unsafe fn available_instance_extensions(entry: &Entry, layer_names: &Vec<CString>) -> Vec<CString> {
        let mut extension_names = Vec::new();

         for layer_name in layer_names {
            let extensions = entry
                .enumerate_instance_extension_properties(Some(&layer_name))
                .expect("Failed to enumerate instance extension properties");


            for extension in extensions {
                let name = CStr::from_ptr(extension.extension_name.as_ptr())
                    .to_str()
                    .expect("Failed to convert extension name to string");

                info!("{:?}", name);
                extension_names.push(CString::from_str(name).expect("Failed to create CString"));
            }
        }
        
    
        extension_names
    }
```

```rust
    unsafe fn available_insatnce_layers(entry: &Entry) -> Vec<CString> {
 
        let layers = entry.enumerate_instance_layer_properties().expect("Layers not found");
        let mut layer_names = vec![];
        for i in &layers {
            let layer_name: &CStr = CStr::from_ptr(i.layer_name.as_ptr());
            layer_names.push(CString::from_str(layer_name.to_str().unwrap()).unwrap());
        }

        return layer_names;
    }
```

**Comment by jack-samo10000** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the available_instance_extensions function to include global extensions and removed the unnecessary loop over layer names. Also fixed a typo in the function name for available_instance_layers.

You can review changes in this commit: https://github.com/jack-samo10000/ash-rs-ash-975/commit/e50bf0ad41b3393d00bf8471e4eb82733a763336.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by olejaaaaaaaa** [comment]
Thank you very much :), now everything works
